# Generated by Django 3.1.5 on 2021-01-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'full time'), ('PT', 'part time')], default='FT', max_length=5),
            preserve_default=False,
        ),
    ]
